---
name: SSH to Google Cloud Platform compute instances
on:
  push:
    branches:
      - main
jobs:
  gcloud-setup:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/96779220803/locations/global/workloadIdentityPools/github-action/providers/shailenevonence'
        service_account: 'github-ssh-poc@infra-devops-activities.iam.gserviceaccount.com'
        
    - name: 'List Compute Instances'
      run: |-
        gcloud compute instances list --project sinfra-devops-activities --zones us-central1-a
